project:
  type: website
  output-dir: docs

render:
      - index.qmd
      - BEN1_2013.qmd
      - BEN2_2013.qmd

website:
  title: "STA3 Interaction spatiale"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - BEN1_2013.qmd
      - BEN2_2013.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true






