project:
  type: website
  output-dir: docs

render:
      - index.qmd
      - cours.qmd
      - BEN1_2013.qmd
      - BEN2_2013.qmd
      - BFA1_2008.qmd
      - BFA2_2008.qmd
      - MLI1_2009.qmd
      - MLI2_2009.qmd
      - SEN1_2013.qmd

website:
  title: "STA3 Interaction spatiale"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cours.qmd
      - BEN1_2013.qmd
      - BEN2_2013.qmd
      - BFA1_2008.qmd
      - BFA2_2008.qmd
      - MLI1_2009.qmd
      - MLI2_2009.qmd      
      - SEN1_2013.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true






